# -*- coding: utf-8 -*-
"""SUMMARIZER FINAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awnQc7e79ZLEGQrExs0n5Qz0sYEn3v6e
"""

!pip install langchain
!pip install openai
!pip install PyPDF2
!pip install faiss-cpu
!pip install tiktoken

!pip install Gradio
import gradio as gr

from PyPDF2 import PdfReader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import ElasticVectorSearch, Pinecone, Weaviate, FAISS

# Get your API keys from openai, you will need to create an account.
# Here is the link to get the keys: https://platform.openai.com/account/billing/overview
import os
from google.colab import userdata
os.environ["OPENAI_API_KEY"] = "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"

os.environ["OPENAI_API_KEY"] = "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"

import requests
from PyPDF2 import PdfReader

pdf_url = 'https://www.cs.cmu.edu/~fgandon/documents/lecture/uk1999/operating_system/operating_system.pdf'

# Fetch the PDF content from the URL
response = requests.get(pdf_url)

# Save the PDF content to a file
with open('downloaded_pdf.pdf', 'wb') as file:
    file.write(response.content)

# Read the PDF file
with open('downloaded_pdf.pdf', 'rb') as file:
    pdf_reader = PdfReader(file)
    # Now you can use the pdf_reader object as needed
    # For example, to get the number of pages:
    num_pages = len(pdf_reader.pages)
    print(f"Number of pages: {num_pages}")

with open('downloaded_pdf.pdf', 'rb') as file:
    pdf_reader = PdfReader(file)

    # Initialize raw_text variable
    raw_text = ''

    # Iterate through pages and extract text
    for i, page in enumerate(pdf_reader.pages):
        text = page.extract_text()
        if text:
            raw_text += text

# raw_text

raw_text[:100]

# We need to split the text that we read into smaller chunks so that during information retreival we don't hit the token size limits.

text_splitter = CharacterTextSplitter(
    separator = "\n",
    chunk_size = 1000,
    chunk_overlap  = 200,
    length_function = len,
)
texts = text_splitter.split_text(raw_text)

len(texts)

texts[0]

texts[1]

# Download embeddings from OpenAI
embeddings = OpenAIEmbeddings()

docsearch = FAISS.from_texts(texts, embeddings)

docsearch

from langchain.chains.question_answering import load_qa_chain
from langchain.llms import OpenAI

chain = load_qa_chain(OpenAI(), chain_type="stuff")

query = "summarize this document in about 800 words"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

def summarize_document(document):
    """Summarizes the given document using LangChain and OpenAI."""

    texts = text_splitter.split_text(document)
    embeddings = OpenAIEmbeddings()
    docsearch = FAISS.from_texts(texts, embeddings)
    chain = load_qa_chain(OpenAI(), chain_type="stuff")
    query = "summarize this document in about 800 words"
    docs = docsearch.similarity_search(query)
    summary = chain.run(input_documents=docs, question=query)
    return summary

# Create the Gradio input interface
iface = gr.Interface(
    summarize_document,
    [gr.Textbox(lines=20, label="Enter a document or paste a PDF link")],
    "textbox",
    title="Document Summarizer",
)
iface.launch()